### ISSUE TITLE
The MAX_METASPACE_SIZE environment variable should be documented

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/metabase-scalingo#5]
https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700000475

**Comment by cprodhomme** [comment]
The app crash with the default config and without this option.
I think you should set the environment variable by default : 
`MAX_METASPACE_SIZE=512m`

**Comment by raphodn** [comment]
Thanks for raising this it helped me out.
My Metabase instance was running slow and had occasional `java.lang.OutOfMemoryError` errors.
Setting `MAX_METASPACE_SIZE=512m` (I'm running an M / 512MB container) in the Scalingo instance's environment fixed it 🎉
